name: CICD for Youtube

on:
  push:
    branches:
      - main

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4  
      - run: npm install
      - run: node server.js

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: | 
              curl -o-  https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh   | bash
              . ~/.nvm.nvm.sh

              nvm instal 14
              npm install -g pm2
              cd ~/CICD
              git pull origin main
              npm install
              npm run build
              pm2 restart api
